import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#e8f5f3',
    },
    keyboardView: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 16,
        backgroundColor: '#e8f5f3',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    headerIcon: {
        fontSize: 20,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2c3e50',
    },
    menuButton: {
        width: 36,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    menuButtonText: {
        fontSize: 24,
        color: '#2c3e50',
        fontWeight: '600',
    },
    messagesList: {
        flex: 1,
        backgroundColor: '#e8f5f3',
    },
    messagesContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        flexGrow: 1,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 40,
        paddingTop: 60,
    },
    emptyAvatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#00ff87',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    emptyAvatarText: {
        fontSize: 28,
        fontWeight: '700',
        color: '#fff',
    },
    emptyTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: 8,
        textAlign: 'center',
    },
    emptySubtitle: {
        fontSize: 18,
        color: '#2c3e50',
        marginBottom: 32,
        textAlign: 'center',
    },
    suggestionsContainer: {
        width: '100%',
        marginTop: 8,
    },
    suggestionCard: {
        backgroundColor: '#fff',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 12,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    suggestionText: {
        fontSize: 15,
        color: '#2c3e50',
        fontWeight: '500',
    },
    messageContainer: {
        marginVertical: 8,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    userMessageContainer: {
        justifyContent: 'flex-end',
        paddingLeft: 60,
    },
    botMessageContainer: {
        justifyContent: 'flex-start',
        paddingRight: 60,
    },
    avatarContainer: {
        marginRight: 10,
        marginTop: 4,
    },
    avatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#fff',
    },
    messageBubble: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 18,
        maxWidth: '100%',
    },
    userMessage: {
        backgroundColor: '#d4f4e7',
        alignSelf: 'flex-end',
        borderBottomRightRadius: 4,
    },
    botMessage: {
        backgroundColor: '#ffffff',
        alignSelf: 'flex-start',
        borderBottomLeftRadius: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
        elevation: 1,
    },
    errorMessage: {
        backgroundColor: '#ffe6e6',
        borderColor: '#ff6b6b',
        borderWidth: 1,
    },
    messageText: {
        fontSize: 15,
        lineHeight: 21,
        letterSpacing: 0.1,
    },
    userMessageText: {
        color: '#2c3e50',
        fontWeight: '400',
    },
    botMessageText: {
        color: '#2c3e50',
        fontWeight: '400',
    },
    errorMessageText: {
        color: '#d32f2f',
        fontStyle: 'italic',
        fontWeight: '500',
    },
    inputContainer: {
        flexDirection: 'row',
        padding: 16,
        paddingBottom: 24,
        backgroundColor: '#e8f5f3',
        alignItems: 'flex-end',
        gap: 8,
    },
    inputWrapper: {
        flex: 1,
        backgroundColor: '#fff',
        borderRadius: 24,
        paddingHorizontal: 16,
        paddingVertical: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
    },
    textInput: {
        fontSize: 15,
        color: '#2c3e50',
        maxHeight: 80,
        minHeight: 20,
        paddingTop: 0,
        paddingBottom: 0,
    },
    inputActions: {
        flexDirection: 'row',
        marginTop: 8,
        marginLeft: -4,
    },
    iconButton: {
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 4,
    },
    iconButtonText: {
        fontSize: 18,
    },
    sendButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#00c4ff',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#00c4ff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    sendButtonDisabled: {
        backgroundColor: '#b0c4de',
        shadowOpacity: 0,
    },
    sendButtonIcon: {
        fontSize: 20,
        color: '#fff',
        fontWeight: '600',
    },
});